version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: infection/infection
    versions:
    - 0.21.0
    - 0.21.1
    - 0.21.2
    - 0.21.3
    - 0.21.4
  - dependency-name: phpunit/phpunit
    versions:
    - 9.5.1
    - 9.5.2
  - dependency-name: phpspec/phpspec
    versions:
    - 7.0.1
